development:
  adapter: mysql
  database: brosis_dev
  username: root
  password: root
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: brosis_pro
  username: susan_db
  password: db_mima
  pool: 5
  timeout: 5000
